# Generated by Django 4.1.3 on 2023-04-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept',
            new_name='name',
        ),
    ]
